# SDLActivity loads SDL as a shared library. Match the app's minimum API level.
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Android)
set(VCPKG_CMAKE_SYSTEM_VERSION 21)
set(VCPKG_CMAKE_CONFIGURE_OPTIONS -DANDROID_ABI=x86_64 -DSDL_ANDROID_JAR=ON)
set(VCPKG_ENV_PASSTHROUGH ANDROID_HOME ANDROID_NDK_HOME JAVA_HOME)
